# Site settings
title: s/v Lark

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://svlark.com' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :year/:month/:title.html

pagination:          true
paginate:            8
paginate_path:       page/:num/

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: false
        # Meta
        show_tags: true
        show_categories: false
        # Social
        share_buttons: true
        disqus: true
